import nodemailer from "nodemailer";
import { env } from "../../config/env.js";

// ---------------------------------------------------------------------------
// Transporter
// ---------------------------------------------------------------------------
export const transporter = nodemailer.createTransport({
  host: env.SMTP_HOST,
  port: env.SMTP_PORT,
  secure: env.SMTP_PORT === 465,
  auth: {
    user: env.SMTP_USER,
    pass: env.SMTP_PASS,
  },
});

export async function sendEmail(subject: string, html: string): Promise<void> {
  await transporter.sendMail({
    from: `"Finance Tracker" <${env.SMTP_USER}>`,
    to: env.EMAIL_TO,
    subject,
    html,
  });
}

// ---------------------------------------------------------------------------
// Shared styles
// ---------------------------------------------------------------------------
const baseStyle = `
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
  background: #f4f6f9;
  padding: 32px 16px;
  margin: 0;
`;

const cardStyle = `
  max-width: 680px;
  margin: 0 auto;
  background: #ffffff;
  border-radius: 12px;
  overflow: hidden;
  box-shadow: 0 2px 12px rgba(0,0,0,0.08);
`;

const headerStyle = (bg: string) => `
  background: ${bg};
  color: #ffffff;
  padding: 28px 32px;
`;

const tableStyle = `
  width: 100%;
  border-collapse: collapse;
  font-size: 14px;
`;

const thStyle = `
  background: #f8f9fa;
  color: #6b7280;
  font-size: 11px;
  font-weight: 600;
  text-transform: uppercase;
  letter-spacing: 0.05em;
  padding: 12px 16px;
  text-align: left;
  border-bottom: 2px solid #e5e7eb;
`;

const tdStyle = `
  padding: 12px 16px;
  border-bottom: 1px solid #f3f4f6;
  color: #374151;
`;

const footerStyle = `
  padding: 20px 32px;
  text-align: center;
  font-size: 12px;
  color: #9ca3af;
  background: #f8f9fa;
`;

// ---------------------------------------------------------------------------
// Template 1: Monthly Transaction Summary
// ---------------------------------------------------------------------------
export interface TransactionRow {
  date: string;
  description: string;
  categoryName: string;
  amount: number; // in paise/smallest unit
}

export function buildMonthlyTransactionEmail(
  month: string,
  year: number,
  rows: TransactionRow[],
  totalPaise: number,
): string {
  const formatAmount = (paise: number) =>
    `₹${(paise / 100).toLocaleString("en-IN", { minimumFractionDigits: 2 })}`;

  const rowsHtml = rows
    .map(
      (r) => `
    <tr>
      <td style="${tdStyle}">${r.date}</td>
      <td style="${tdStyle}">${r.description || "—"}</td>
      <td style="${tdStyle}">${r.categoryName}</td>
      <td style="${tdStyle}; text-align: right; font-weight: 500;">${formatAmount(r.amount)}</td>
    </tr>`,
    )
    .join("");

  return `
<!DOCTYPE html>
<html>
<head><meta charset="utf-8"><title>Monthly Summary</title></head>
<body style="${baseStyle}">
  <div style="${cardStyle}">
    <div style="${headerStyle("#1a2744")}">
      <h1 style="margin:0; font-size:22px; font-weight:700;">📊 Monthly Spending Summary</h1>
      <p style="margin:6px 0 0; opacity:0.8; font-size:14px;">${month} ${year}</p>
    </div>

    <div style="padding: 24px 32px;">
      <table style="${tableStyle}">
        <thead>
          <tr>
            <th style="${thStyle}">Date</th>
            <th style="${thStyle}">Description</th>
            <th style="${thStyle}">Category</th>
            <th style="${thStyle}; text-align: right;">Amount</th>
          </tr>
        </thead>
        <tbody>
          ${rowsHtml || `<tr><td colspan="4" style="${tdStyle}; text-align:center; color:#9ca3af;">No transactions this month.</td></tr>`}
        </tbody>
        <tfoot>
          <tr>
            <td colspan="3" style="padding: 14px 16px; font-weight: 700; font-size: 15px; color: #1a2744; border-top: 2px solid #e5e7eb;">
              Grand Total
            </td>
            <td style="padding: 14px 16px; font-weight: 700; font-size: 15px; color: #1a2744; text-align: right; border-top: 2px solid #e5e7eb;">
              ${formatAmount(totalPaise)}
            </td>
          </tr>
        </tfoot>
      </table>
    </div>

    <div style="${footerStyle}">
      Generated by Finance Tracker · ${month} ${year}
    </div>
  </div>
</body>
</html>`;
}

// ---------------------------------------------------------------------------
// Template 2: Credits Billing Reminder
// ---------------------------------------------------------------------------
export interface CreditRow {
  description: string;
  categoryName: string;
  amount: number; // in paise
  billedDate: string;
  paymentDate: string;
  paidStatus: boolean;
}

export function buildCreditsBillingEmail(
  month: string,
  year: number,
  rows: CreditRow[],
): string {
  const formatAmount = (paise: number) =>
    `₹${(paise / 100).toLocaleString("en-IN", { minimumFractionDigits: 2 })}`;

  const rowsHtml = rows
    .map(
      (r) => `
    <tr>
      <td style="${tdStyle}">${r.description}</td>
      <td style="${tdStyle}">${r.categoryName}</td>
      <td style="${tdStyle}; text-align: right; font-weight: 500;">${formatAmount(r.amount)}</td>
      <td style="${tdStyle}">${r.billedDate}</td>
      <td style="${tdStyle}">${r.paymentDate}</td>
      <td style="${tdStyle}; text-align: center;">
        <span style="
          display: inline-block;
          padding: 2px 10px;
          border-radius: 99px;
          font-size: 11px;
          font-weight: 600;
          background: ${r.paidStatus ? "#dcfce7" : "#fef2f2"};
          color: ${r.paidStatus ? "#16a34a" : "#dc2626"};
        ">${r.paidStatus ? "Paid" : "Unpaid"}</span>
      </td>
    </tr>`,
    )
    .join("");

  return `
<!DOCTYPE html>
<html>
<head><meta charset="utf-8"><title>Credits Billing</title></head>
<body style="${baseStyle}">
  <div style="${cardStyle}">
    <div style="${headerStyle("#b45309")}">
      <h1 style="margin:0; font-size:22px; font-weight:700;">💳 Credits Due Today</h1>
      <p style="margin:6px 0 0; opacity:0.8; font-size:14px;">Billed on the 15th · ${month} ${year}</p>
    </div>

    <div style="padding: 24px 32px;">
      <table style="${tableStyle}">
        <thead>
          <tr>
            <th style="${thStyle}">Description</th>
            <th style="${thStyle}">Category</th>
            <th style="${thStyle}; text-align: right;">Amount</th>
            <th style="${thStyle}">Billed Date</th>
            <th style="${thStyle}">Payment Date</th>
            <th style="${thStyle}; text-align: center;">Status</th>
          </tr>
        </thead>
        <tbody>
          ${rowsHtml || `<tr><td colspan="6" style="${tdStyle}; text-align:center; color:#9ca3af;">No credits billed today.</td></tr>`}
        </tbody>
      </table>
    </div>

    <div style="${footerStyle}">
      Generated by Finance Tracker · ${month} ${year}
    </div>
  </div>
</body>
</html>`;
}
